### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by tylernchls** [lholmquist/angular-web-app#2]
Build fails after trying to move the built application

npm info ok
---> Cleaning up npm cache
----> moving built web application to /opt/app-root/output
mv: cannot stat './build/*': No such file or directory
error: build error: non-zero (13) exit code from nodeshift/centos7-s2i-web

**Comment by lholmquist** [comment]
doesn't look like you are setting the OUTPUT_DIR env variable.

see here:  https://github.com/lholmquist/angular-web-app#running-on-openshift

**Comment by tylernchls** [comment]
Great thank you that did the trick!

**Comment by vinay-83** [comment]
> doesn't look like you are setting the OUTPUT_DIR env variable.
> 
> see here: https://github.com/lholmquist/angular-web-app#running-on-openshift
----------------------------------------------------------------------------------------------
----> moving built web application to /opt/app-root/output
mv: cannot stat './dist/myworld-web-app/*': No such file or directory
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1


Added OUTPUT_DIR still the issue is persist
But your
https://github.com/lholmquist/angular-web-app.git
this angular app was running sucessfully
difference is .openshiftio this folder is not present in my github repo
how can i solve it,And what is the importance of .openshiftio this file

Thanks in advance....
